namespace OpenCLNet {
	public enum KernelWorkGroupInfo {
		WORK_GROUP_SIZE = 0x11B0,
		COMPILE_WORK_GROUP_SIZE = 0x11B1,
		LOCAL_MEM_SIZE = 0x11B2,
		PREFERRED_WORK_GROUP_SIZE_MULTIPLE = 0x11B3,
		PRIVATE_MEM_SIZE = 0x11B4
	}
}